development:
  adapter: postgresql
  encoding: unicode
  database: feedback_mvp_development
  pool: 5
  username: user
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: feedback_mvp_test
  pool: 5
  username: user
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: feedback_mvp_production
  pool: 5
  username: feedback_mvp
  password:
